/*
HAVING İLE WHERE KARIŞTIRILMAMALI!

HAVING SADECE GROUP'LAMA İŞLEMLERİNDE KULLANILIR.
WHERE İSE SATIRLARI FİLTRELER!
SELECT rental_rate, COUNT(*) FROM film GROUP BY rental_rate HAVING COUNT(*) > 325;
*/